### ISSUE TITLE
Match History

### ISSUE THREAD

**Issue by BobbyESP** [RumbleMike/ValorantRankedPoints#1]
There's a way to put more matches than the last?

**Comment by RumbleMike** [comment]
Yup, api pulls up to 20 matches. Although these matches are mixed with unrated games aswell. So you have to sort through all matches.

**Comment by floxay** [comment]
As RumbleMike said, yes, it is possible but limited to a maximum of 20 matches/request.

Just change the `startIndex` and `endIndex` parameters from 0 and 20 to 20 and 40 and so on.

**Comment by RumbleMike** [comment]
Flox, i don't think it can go past 20, it seems to cause issues on my end.

**Comment by floxay** [comment]
It definitely can, just checked again, check your params.

**Comment by RumbleMike** [comment]
Weird, always bugs out when i try to do something like that.
