### ISSUE TITLE
I cannot find the zip folder!!

### ISSUE THREAD

**Issue by SiddharthGautam1** [RumbleMike/ValorantRankedPoints#15]
Please help me I cannot find the RankedPointsChecker.zip folder.. Pls help me!!

**Comment by TJ2005** [comment]
Hey bro same I get the source code instead ;-;

**Comment by TJ2005** [comment]
Hey brother I think I figured it out https://www.youtube.com/watch?v=cP3Ly3-4kSI watch this video we are in the wrong repo bruh moment

**Comment by SiddharthGautam1** [comment]
oh lol thanks for answering tho
